spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board2?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include: mysql

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLXNlaHllb24tc3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFs